apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.19.0.20-172.19.0.50 # note that these must be updated from docker inspect, like 172.18.0.20-172.18.0.50
