name: Update niv

on:
  schedule:
    # every day at 8am UTC
    - cron: '0 8 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - uses: cachix/install-nix-action@v11
    # https://github.com/nmattia/niv/issues/280
    - run: GITHUB_PATH= nix-shell --run "niv update"
    # TODO: Up to the authors of Waypoint to set up a binary cache at cachix.org
    # - uses: cachix/cachix-action@v6
    #  with:
    #    name: waypoint
    #    signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --run "go version"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
